// read logs from database generated by attack scripts @kali-attacker-machine

import  {selectRows} from "@/app/lib/read_db.js"



import encrypt from "@/app/lib/encrypt"
import decrypt from "@/app/lib/decrypt"

export async function GET(request){
    try{
        const logs = await selectRows()
        
        const encryptedData = encrypt({logs : logs})
        return new Response(JSON.stringify({ encryptedData }))

        // return new Response(JSON.stringify(logs))
    } catch(error){
        console.debug(error)
        const encryptedData = encrypt({status : false})
        return new Response(JSON.stringify({ encryptedData }))
        // return new Response(JSON.stringify({status : false}))
        
    }

}

