// read logs from database generated by attack scripts @kali-attacker-machine

import  {selectRows} from "@/app/lib/read_db.js"

export async function GET(request){
    try{
        const logs = await selectRows()
        return new Response(JSON.stringify(logs))
    } catch(error){
        console.debug(error)
        return new Response(JSON.stringify({status : false}))
        
    }

}

