import './globals.css'
import { Inter } from 'next/font/google'


// import sidebar

// import Sidebar from './components/Sidebar'

import Providers from './components/Providers'


import Header from './components/Header/Header'


const inter = Inter({ subsets: ['latin'] })


// import NextTopLoader from 'nextjs-toploader';

import TopLoader from "@/app/components/TopLoader"
import WebIcon from "@/app/components/WebIcon"


// import './vendor/remixicons/remixicon.css'
import 'aos/dist/aos.css';


export const metadata = {
  title: 'Attack & Defense - Q',
  // description: 'Generated by create next app',
}


// const WebIcon = () => {
//   return (
//     <link rel="icon" href={"/assets/img/new_logo.ico"} sizes="any" />
//   )
// }




export default function RootLayout({ children }) {
  return (
    <html lang="en"  >
      <WebIcon />
      <body className={inter.className  + "  theme-color "}>
        <Providers >
          <TopLoader />
          <main className=' min-h-screen  ' >
            <Header />
            {children}
          </main>
        </Providers>
        </body>
    </html>
  )
}
