import './globals.css'
import { Inter } from 'next/font/google'


// import sidebar

import Sidebar from './components/Sidebar'

import Providers from './components/Providers'


import Header from './components/Header'


const inter = Inter({ subsets: ['latin'] })


import NextTopLoader from 'nextjs-toploader';


import './vendor/remixicons/remixicon.css'


export const metadata = {
  title: 'NeoRix',
  // description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en"  >
      <body className={inter.className}>
        <Providers >
          
        <NextTopLoader
  color="#1e40af"
  initialPosition={0.08}
  crawlSpeed={200}
  height={5}
  crawl={true}
  showSpinner={false}
  easing="ease"
  speed={200}
  shadow="0 0 10px #2299DD,0 0 5px #2299DD"
/>
          <Sidebar>
          <Header />
            {children}
          </Sidebar>
        </Providers>
        </body>
    </html>
  )
}
