import './globals.css'
import { Inter } from 'next/font/google'


// import sidebar

import Sidebar from './components/Sidebar'

import Providers from './components/Providers'


import Header from './components/Header'


const inter = Inter({ subsets: ['latin'] })


import NextTopLoader from 'nextjs-toploader';


import './vendor/remixicons/remixicon.css'


export const metadata = {
  title: 'Attack & Defense - Q',
  // description: 'Generated by create next app',
}



export default function RootLayout({ children }) {
  return (
    <html lang="en"  >
      <link rel="icon" href="/assets/img/logo_new.ico" sizes="any" />
      <body className={inter.className }>
        <Providers >
          
        <NextTopLoader
  color="#ec4899"
  initialPosition={0.08}
  crawlSpeed={200}
  height={7}
  crawl={true}
  showSpinner={false}
  easing="ease"
  speed={200}
  shadow="0 0 10px #be123c,0 0 5px #be123c"
/>
          <Sidebar>
          <Header />
          <main className=' min-h-screen theme-color ' >
            {children}
          </main>
          </Sidebar>
        </Providers>
        </body>
    </html>
  )
}
