import { FaFire, FaLock, FaBug, FaExclamationCircle, /* ... */ } from 'react-icons/fa';
import { AiOutlineEye, AiOutlineGlobal,  /* ... */ } from 'react-icons/ai';
import { FaMicroscope, FaRobot, FaHandRock, FaMemory, /* ... */ } from 'react-icons/fa';
import { AiOutlineDesktop,  AiFillSafetyCertificate, AiOutlineSearch, /* ... */ } from 'react-icons/ai';
import { FaMask, FaTag, FaMapSigns, /* ... */ } from 'react-icons/fa';
import { AiOutlineTerminal, AiOutlineUserSecret, AiOutlineCloudUploadAlt, /* ... */ } from 'react-icons/ai';
import { FaBoxOpen, FaUserLock, FaVirus, FaGlobe, /* ... */ } from 'react-icons/fa';
import { AiOutlineUserCheck, AiOutlineMicroscope, AiOutlineRobot, /* ... */ } from 'react-icons/ai';
import { FaArrowsAltH, FaDatabase, FaSearchPlus, FaArrowRight , FaUserCheck , /* ... */ } from 'react-icons/fa';
import { AiOutlineApi, AiOutlineKey, AiOutlineWifi, /* ... */ } from 'react-icons/ai';
import { FaShieldAlt, FaEye, FaTimes, FaUserSecret, FaFingerprint , FaCloudUploadAlt, FaCodeBranch, FaFileSignature, FaCogs, FaKeyboard, FaIdBadge , FaBinoculars , FaUndo , FaExclamationTriangle , FaShare, FaKey, FaObjectUngroup,  /* ... */ } from 'react-icons/fa';
import { BsFingerprint } from 'react-icons/bs';
// import {FaUserSecret} from "react-icons/fa";
import { TbMicroscope , TbFileCertificate } from "react-icons/tb";
import {HiOutlineShieldCheck} from "react-icons/hi";






export  const cybersecurityIcons = {
    "Default": <FaShieldAlt />,
    "Firewall": <FaFire />,
    "Encryption": <FaLock />,
    "Malware": <FaBug />,
    "Vulnerability": <FaExclamationCircle />,
    "Intrusion Detection": <AiOutlineEye />,
    "Network Security": <AiOutlineGlobal />,
    "Authentication": <BsFingerprint />,
    "Application Security Testing": <FaMicroscope />,
    "Automated Security Testing": <FaRobot />,
    "Behavioral Analysis": <FaUserCheck />,
    "Biometric Authentication": <FaFingerprint />,
    "Bot Detection": <FaRobot />,
    "Brute Force Attack": <FaHandRock />,
    "Buffer Overflow": <FaMemory />,
    "Business Continuity Planning": <FaShieldAlt />,
    "Cloud Access Security Broker (CASB)": <FaCloudUploadAlt />,
    "Code Review": <FaCodeBranch />,
    "Dark Web Monitoring": <FaMask />,
    "Data Classification": <FaTag />,
    "Data Loss Prevention": <FaDatabase />,
    "Deception Technology": <FaMapSigns />,
    "Digital Certificate": <AiFillSafetyCertificate />,
    "Digital Signature": <FaFileSignature />,
    "Endpoint Detection and Response (EDR)": <AiOutlineDesktop />,
    "Ethical Hacking": <FaUserSecret />,
    "File Integrity Monitoring (FIM)": <FaBoxOpen />,
    "Firewall Configuration": <FaCogs />,
    "Fuzz Testing": <TbMicroscope />,
    "Honeypot": <FaBoxOpen />,
    "Incident Analysis": <AiOutlineSearch />,
    "Insider Threat": <FaUserSecret />,
    "Integrity Verification": <HiOutlineShieldCheck />,
    "Internet of Things (IoT) Security": <AiOutlineApi />,
    "Keylogger": <FaKeyboard />,
    "Man-in-the-Middle (MitM) Attack": <FaArrowsAltH />,
    "Network Forensics": <FaSearchPlus />,
    "Man-in-the-Middle (MitM) Attack": <FaArrowsAltH />,
    "Network Forensics": <FaSearchPlus />,
    "Outbound Firewall": <FaArrowRight />,
    "Database Security": <FaDatabase />,
    "Digital Identity": <FaIdBadge />,
    "Biometric Authentication": <FaFingerprint />,
    "Threat Hunting": <FaBinoculars />,
    "Security Monitoring": <FaEye />,
    "Adaptive Security": <AiOutlineApi />,
    "Public Key Infrastructure (PKI)": <AiOutlineKey />,
    "Wireless Network Security": <AiOutlineWifi />,
    "Security Posture": <FaShieldAlt />,
    "Integrity Verification": <HiOutlineShieldCheck />,
    "Incident Recovery": <FaUndo />,
    "Security Incident Management": <FaExclamationTriangle />,
    "Data Breach": <FaTimes />,
    "Insider Threat": <FaUserSecret />,
    "Threat Intelligence Sharing": <FaShare />,
    "Security Token": <FaKey />,
    "Firewall Configuration": <FaCogs />,
    "Network Segmentation": <FaObjectUngroup />,
    "Wireless Network Security": <AiOutlineWifi />,
    "Internet of Things (IoT) Security": <AiOutlineApi />,
    "Certificate Authority": <TbFileCertificate />,
    // ... add more terms and icons
};



// const cybersecurityIcons = {
//     "Firewall": "fire",
//     "Encryption": "lock",
//     "Malware": "bug",
//     "Vulnerability": "exclamation-circle",
//     "Intrusion Detection": "eye",
//     "Network Security": "network-wired",
//     "Authentication": "fingerprint",
//     "Access Control": "shield-alt",
//     "Phishing": "envelope",
//     "Data Breach": "user-secret",
//     "Cyber Attack": "skull-crossbones",
//     "Cyber Threat": "radiation",
//     "Incident Response": "medkit",
//     "Digital Forensics": "search",
//     "Zero-Day Exploit": "bomb",
//     "Ransomware": "money-bill-wave",
//     "Social Engineering": "user-friends",
//     "Two-Factor Authentication": "key",
//     "Penetration Testing": "user-ninja",
//     "Patch Management": "tools",
//     "Security Audit": "clipboard-check",
//     "Endpoint Security": "desktop",
//     "DNS Security": "globe",
//     "Firewall Rules": "list",
//     "IoT Security": "microchip",
//     "Network Segmentation": "sitemap",
//     "VPN": "globe-americas",
//     "Antivirus": "shield-virus",
//     "Cryptography": "code",
//     "Phishing Email": "envelope-open-text",
//     "Incident Handling": "hands-helping",
//     "Security Awareness": "brain",
//     "Threat Intelligence": "search-dollar",
//     "Web Application Security": "window-maximize",
//     "Cybersecurity Framework": "th-list",
//     "Hacking": "user-secret",
//     "Cyber Hygiene": "hands-wash",
//     "Data Protection": "shield",
//     "Network Monitoring": "signal",
//     "Privacy": "user-lock",
//     "Secure Coding": "keyboard",
//     "Biometric Security": "fingerprint",
//     "Identity and Access Management": "user-check",
//     "Cloud Security": "cloud",
//     "Container Security": "cubes",
//     "Secure Development": "laptop-code",
//     "Security Operations Center": "shield-alt",
//     "Security Incident": "exclamation-triangle",
//     "Cybersecurity Training": "graduation-cap",
//     "Wireless Security": "wifi",
//     "Security Architecture": "sitemap",
//     "Security Controls": "sliders-h",
//     "Security Compliance": "clipboard-list",
//     "Security Patch": "shield-alt",
//     "Security Threat Analysis": "chart-area",
//     "Security Best Practices": "lightbulb",
//     "Secure Network": "globe",
//     "Security Training": "graduation-cap",
//     "Security Policy": "file-alt",
//     "Security Risk Management": "balance-scale",
//     "Security Strategy": "bullseye",
//     "Security Standards": "cogs",
//     "Security Awareness Training": "users",
//     "Cybersecurity Governance": "gavel",
//     "Network Access Control": "network-wired",
//     "Incident Reporting": "flag",
//     "Application Security": "code",
//     "Digital Identity": "id-badge",
//     "Forensic Analysis": "search",
//     "Incident Investigation": "search-minus",
//     "Security Posture": "chart-bar",
//     "Secure Communication": "comments",
//     "Network Segregation": "object-ungroup",
//     "Security Compliance Audit": "clipboard-check",
//     "Data Encryption": "unlock-alt",
//     "Threat Mitigation": "hands-helping",
//     "Secure File Sharing": "file-upload",
//     "Mobile Security": "mobile",
//     "Secure Browsing": "shield-check",
//     "Security Testing": "flask",
//     "Multi-Factor Authentication": "user-shield",
//     "Cybersecurity Awareness": "user-headset",
//     "Secure Storage": "hdd",
//     "Firewall Configuration": "sliders-h",
//     "Security Analysis": "chart-line",
//     "Cybersecurity Education": "book-reader",
//     "Security Incident Response Plan": "file-medical-alt",
//     "Security Monitoring": "binoculars",
//     "Security Operations": "shield-alt",
//     "Security Controls": "sliders-h",
//     "Security Compliance": "clipboard-list",
//     "Security Patch": "shield-alt",
//     "Security Threat Analysis": "chart-area",
//     "Security Best Practices": "lightbulb",
//     "Secure Network": "globe",
//     "Security Training": "graduation-cap",
//     "Security Policy": "file-alt",
//     "Security Risk Management": "balance-scale",
//     "Security Strategy": "bullseye",
//     "Security Standards": "cogs",
//     "Security Awareness Training": "users",
//     "Cybersecurity Governance": "gavel",
//     "Network Access Control": "network-wired",
//     "Incident Reporting": "flag",
//     "Application Security": "code",
//     "Digital Identity": "id-badge",
//     "Forensic Analysis": "search",
//     "Incident Investigation": "search-minus",
//     "Security Posture": "chart-bar",
//     "Secure Communication": "comments",
//     "Network Segregation": "object-ungroup",
//     "Security Compliance Audit": "clipboard-check",
//     "Data Encryption": "unlock-alt",
//     "Threat Mitigation": "hands-helping",
//     "Secure File Sharing": "file-upload",
//     "Mobile Security": "mobile",
//     "Secure Browsing": "shield-check",
//     "Security Testing": "flask",
//     "Multi-Factor Authentication": "user-shield",
//     "Cybersecurity Awareness": "user-headset",
//     "Secure Storage": "hdd",
//     "Firewall Configuration": "sliders-h",
//     "Security Analysis": "chart-line",
//     "Cybersecurity Education": "book-reader",
//     "Security Incident Response Plan": "file-medical-alt",
//     "Cybersecurity Program": "sitemap",
//     "Security Breach": "skull",
//     "Security Consultant": "user-tie",
//     "Security Engineering": "hard-hat",
//     "Security Hardening": "shield-check",
//     "Security Investigation": "magnifying-glass",
//     "Security Management": "tasks",
//     "Security Operations Center (SOC)": "shield-alt",
//     "Security Policy Enforcement": "user-shield",
//     "Security Review": "check-double",
//     "Security Software": "software",
//     "Security Team": "users-cog",
//     "Security Token": "key",
//     "Security Update": "cloud-upload-alt",
//     "Threat Detection": "search-dollar",
//     "Security Awareness Program": "brain",
//     "Security Incident Management": "exclamation-triangle",
//     "Security Operations Center (SOC)": "shield-alt",
//     "Security Patch Management": "file-medical",
//     "Security Policy Enforcement": "user-shield",
//     "Security Policy Review": "scroll",
//     "Security Program Management": "sitemap",
//     "Security Research": "search",
//     "Security Risk Assessment": "balance-scale-left",
//     "Security Risk Mitigation": "balance-scale-right",
//     "Security Solution": "cogs",
//     "Security Training Program": "graduation-cap",
//     "Security Vulnerability Assessment": "file-contract",
//     "Social Media Security": "comment-dots",
//     "Software Security": "code",
//     "Supply Chain Security": "people-carry",
//     "System Security": "desktop",
//     "Threat Intelligence Sharing": "user-shield",
//     "Threat Modeling": "chart-pie",
//     "User Access Management": "user-lock",
//     "Virus Scan": "virus",
//     "Web Security": "globe",
//     "Wireless Network Security": "wifi",
//     "Zero Trust": "shield-alt",
//     "Application Security Testing": "microscope",
//     "Automated Security Testing": "robot",
//     "Behavioral Analysis": "user-check",
//     "Biometric Authentication": "fingerprint",
//     "Bot Detection": "robot",
//     "Brute Force Attack": "hand-rock",
//     "Buffer Overflow": "memory",
//     "Business Continuity Planning": "shield-alt",
//     "Cloud Access Security Broker (CASB)": "cloud-upload-alt",
//     "Code Review": "code-branch",
//     "Command Injection": "terminal",
//     "Computer Emergency Response Team (CERT)": "user-shield",
//     "Container Security": "cubes",
//     "Cyber Insurance": "umbrella",
//     "Cybersecurity Framework": "th-list",
//     "Cybersecurity Incident": "exclamation-triangle",
//     "Cybersecurity Maturity Model Certification (CMMC)": "certificate",
//     "Cybersecurity Policy": "file-contract",
//     "Cybersecurity Training": "graduation-cap",
//     "Dark Web Monitoring": "mask",
//     "Data Classification": "tag",
//     "Data Loss Prevention": "database",
//     "Deception Technology": "map-signs",
//     "Denial of Service (DoS)": "ban",
//     "Digital Certificate": "certificate",
//     "Digital Signature": "signature",
//     "Endpoint Detection and Response (EDR)": "desktop",
//     "Ethical Hacking": "user-shield",
//     "Exploit": "bomb",
//     "File Integrity Monitoring (FIM)": "shield-alt",
//     "Firewall Configuration": "cogs",
//     "Fuzz Testing": "microscope",
//     "Honeypot": "box-open",
//     "Incident Analysis": "search",
//     "Insider Threat": "user-secret",
//     "Integrity Verification": "shield-check",
// };